### ISSUE TITLE
Shop Items / Shop Packages

### ISSUE THREAD

**Issue by KumariAshamaki** [CodingByHarry/scum_discord_bot_os#2]
Hi I am trying to add items to the shop and I assume you have to add them to the db and then run the command in discord my issue is I seem to not be able to do it correctly could I have an example of how you would add items to the shop?

I think my issue is I am not sure what is meant by spawn type.

**Comment by CodingByHarry** [comment]
Sorry I Haven't looked at it since it was pushed. You'll need to read the code and try work backwards to determine what that field is - I haven't the slightest!

**Comment by KumariAshamaki** [comment]
Ah I feared you would say that lol no worries I will sort it thank you

**Comment by ThouShallLearn** [comment]
Kumari, could we get in touch, having a little trouble getting this working and wanted to see if i could get your assistance.
