### ISSUE TITLE
!Pay issue.

### ISSUE THREAD

**Issue by ThouShallLearn** [CodingByHarry/scum_discord_bot_os#3]
Even when the pay command goes through and deducts/sends the money, it replies with "There was an error while executing this command!" and comes up with a "endsWith" error in the console? We don't have it connected to a scum server yet and was just testing stuff, don't know if that has anything do with the issue or not.

**Comment by CodingByHarry** [comment]
Sorry I don't support the bot :( You will need to debug the code and see what the cause of this issue is.

The error comes from executing the command https://github.com/CodingByHarry/scum_discord_bot_os/blob/main/discord_bot.js line 125
